"""Read-only localhost integration tests. Run: python tests/report_export_test.py.
PDF QA requires PyMuPDF; the temporary local QA installation is used if present.
"""
from pathlib import Path
import subprocess, os, json, socket, time, urllib.request, urllib.parse, urllib.error, sys, re
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'tmp/pdfs/qa'))
import pymupdf as fitz
PHP=r'C:\xampp\php\php.exe'
ENV=os.environ.copy(); ENV['SECUREPOS_ENV']='local'; ENV.pop('SECUREPOS_BASE_URL',None)
fixture=ROOT/'tests/audit_export_fixture.php'
def cli(mode,filters,role='Manager'):
 r=subprocess.run([PHP,str(fixture),mode,json.dumps(filters),role],capture_output=True,env=ENV,cwd=ROOT)
 assert r.returncode==0 and not r.stderr,(r.returncode,r.stderr.decode(errors='replace'))
 return r.stdout
class NoRedirect(urllib.request.HTTPRedirectHandler):
 def redirect_request(self,*args): return None
opener=urllib.request.build_opener(NoRedirect())
sock=socket.socket(); sock.bind(('127.0.0.1',0)); port=sock.getsockname()[1]; sock.close()
sessions=ROOT/'tmp/pdfs/sessions'; sessions.mkdir(parents=True,exist_ok=True)
router=ROOT/'tmp/pdfs/audit-test-router.php'
router.write_text("<?php\nif (PHP_SAPI !== 'cli-server') exit;\n$_SERVER['SERVER_ADDR']='127.0.0.1';\n$script=basename(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH));\nif(in_array($script,['login.php','audit_logs.php','audit_logs_export.php'],true)) { require dirname(__DIR__,2).'/'.$script; } else { return false; }\n")
log=open(ROOT/'tmp/pdfs/audit-http-test.log','wb')
server=subprocess.Popen([PHP,'-d','session.save_path='+str(sessions),'-S',f'127.0.0.1:{port}','-t',str(ROOT),str(router)],stdout=log,stderr=log,env=ENV,cwd=ROOT,creationflags=subprocess.CREATE_NO_WINDOW)
base=f'http://127.0.0.1:{port}/'
created=[]
def request(path,cookie=None):
 req=urllib.request.Request(base+path,headers={'Cookie':'PHPSESSID='+cookie} if cookie else {})
 try:
  with opener.open(req,timeout=30) as response: return response.status,response.headers,response.read()
 except urllib.error.HTTPError as error: return error.code,error.headers,error.read()
def compact(text): return re.sub(r'\s+',' ',str(text)).strip()
try:
 for _ in range(50):
  try: request('login.php'); break
  except urllib.error.URLError: time.sleep(.1)
 original=json.loads(cli('snapshot',{}))
 cookies={}
 for role in ['Manager','Cashier','Inventory Staff']:
  cookies[role]=cli('session',{},role).decode(); created.append(cookies[role])
 for cookie in [None,cookies['Cashier'],cookies['Inventory Staff']]:
  status,headers,body=request('audit_logs_export.php',cookie)
  assert status==302 and headers.get('Location')=='login.php' and not body.startswith(b'%PDF')
 print('PASS: anonymous, Cashier and Inventory Staff direct access rejected')
 for query in ['module=Unknown','result=Unknown','risk=Unknown','actor[]=x','actor='+('x'*101),'start_date=2026-02-30','start_date=2026-10-08&end_date=2026-10-07','actor=%00bad','role=Manager']:
  status,_,body=request('audit_logs_export.php?'+query,cookies['Manager']); assert status==400,(query,status)
 assert json.loads(cli('snapshot',{}))==original,'Rejected requests wrote audit records'
 print('PASS: invalid filters rejected without audit writes')
 actor=next((r['actor_name'] for r in reversed(original) if r['actor_name']), '')
 cases=[('all',{}),('module',{'module':'Authentication'}),('result',{'result':'Failed'}),('risk',{'risk':'high'}),('actor',{'actor':actor}),('date',{'start_date':'2026-09-01','end_date':'2026-10-07'}),('combined',{'module':'Authentication','result':'Rejected','risk':'high'}),('empty',{'actor':'Nonexistent-Audit-Export-Test'})]
 successes=0
 for label,query in cases:
  expected=json.loads(cli('data',query)); rows=expected['rows']; qs=urllib.parse.urlencode(expected['filters'],quote_via=urllib.parse.quote)
  status,_,html=request('audit_logs.php?'+qs,cookies['Manager']); assert status==200 and b'Export PDF' in html
  assert ('audit_logs_export.php?'+qs.replace('&','&amp;')).encode() in html
  assert (str(len(rows))+' result').encode() in html
  status,headers,pdf=request('audit_logs_export.php?'+qs,cookies['Manager'])
  assert status==200 and headers.get_content_type()=='application/pdf' and pdf.startswith(b'%PDF-'),(label,status,pdf[:100])
  successes+=1
  path=ROOT/'tmp/pdfs'/f'audit-{label}.pdf'; path.write_bytes(pdf)
  document=fitz.open(stream=pdf,filetype='pdf'); text=' '.join(page.get_text() for page in document)
  normalized=re.sub(r'\s+','',text)
  assert 'Audit Log Report' in text and 'Generated by:' in text and 'Security Audit Report' in text
  assert re.search(r'Generated: \d{2} [A-Za-z]+ \d{4}, [1-9]\d?:\d{2} (AM|PM)',text)
  assert 'Asia/Kuala_Lumpur' not in text
  assert f'Matching audit records: {len(rows)}' in text
  for row in rows:
   for key in ['actor_name','actor_role','module','action','description']:
    if row[key]: assert re.sub(r'\s+','',row[key]) in normalized,(label,key,'PDF omitted record data')
  for page in document:
   ptext=page.get_text()
   assert re.search(r'Page \d+ of \d+',ptext)
   assert 'Description' in ptext and 'Date & Time' in ptext,'Missing repeated table header'
   for word in page.get_text('words'):
    assert word[0]>=10*72/25.4 and word[2]<=286*72/25.4 and word[1]>=8*72/25.4 and word[3]<=204*72/25.4,'Text outside page bounds'
  after=json.loads(cli('snapshot',{}))
  assert len(after)==len(original)+successes,'Unexpected audit write count'
  assert after[-1]['module']=='Reports' and after[-1]['action']=='Export Audit Log PDF' and after[-1]['result']=='Success'
  assert f'{len(rows)} matching records' in after[-1]['description']
  if label=='all':
   assert len(document)>1,'Multi-page export not exercised'
   for index in [0,1,len(document)-1]: document[index].get_pixmap(matrix=fitz.Matrix(1.4,1.4)).save(str(ROOT/'tmp/pdfs'/f'audit-page-{index+1}.png'))
  print('PASS:',label,len(rows),'records exported;',len(document),'pages; matching page/filter count and logged export')
 final=json.loads(cli('snapshot',{})); final_by_id={r['id']:r for r in final}
 assert all(final_by_id[r['id']]==r for r in original),'Existing audit record modified'
 logtext=(ROOT/'tmp/pdfs/audit-http-test.log').read_text(encoding='utf-8')
 assert not any(x in logtext for x in ['PHP Warning','PHP Fatal','PHP Deprecated','PHP Parse'])
 print('PASS: all original audit rows unchanged; no PHP errors;',successes,'new export events')
finally:
 server.terminate(); server.wait(timeout=10); log.close()
 for sid in created:
  path=sessions/('sess_'+sid)
  if path.is_file(): path.unlink()
