"""Read-only localhost integration tests. Run: python tests/report_export_test.py.
PDF QA requires PyMuPDF; the temporary local QA installation is used if present.
"""
from pathlib import Path
import subprocess, os, json, socket, time, urllib.request, urllib.parse, urllib.error, sys, re
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'tmp/pdfs/qa'))
import pymupdf as fitz
PHP=r'C:\xampp\php\php.exe'
ENV=os.environ.copy(); ENV['SECUREPOS_ENV']='local'; ENV.pop('SECUREPOS_BASE_URL',None)
fixture=ROOT/'tests/report_export_fixture.php'
def cli(mode,filters,role='Manager'):
 r=subprocess.run([PHP,str(fixture),mode,json.dumps(filters),role],capture_output=True,env=ENV,cwd=ROOT)
 assert r.returncode==0 and not r.stderr,(r.returncode,r.stderr.decode(errors='replace'))
 return r.stdout
class NoRedirect(urllib.request.HTTPRedirectHandler):
 def redirect_request(self,*args): return None
opener=urllib.request.build_opener(NoRedirect())
sock=socket.socket(); sock.bind(('127.0.0.1',0)); port=sock.getsockname()[1]; sock.close()
sessions=ROOT/'tmp/pdfs/sessions'; sessions.mkdir(parents=True,exist_ok=True)
router=ROOT/'tmp/pdfs/test-router.php'
router.write_text("<?php\nif (PHP_SAPI !== 'cli-server') exit;\n$_SERVER['SERVER_ADDR']='127.0.0.1';\n$script=basename(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH));\nif(in_array($script,['login.php','reports.php','reports_export.php'],true)) { require dirname(__DIR__,2).'/'.$script; } else { return false; }\n")
log=open(ROOT/'tmp/pdfs/http-test.log','wb')
server=subprocess.Popen([PHP,'-d','session.save_path='+str(sessions),'-S',f'127.0.0.1:{port}','-t',str(ROOT),str(router)],stdout=log,stderr=log,env=ENV,cwd=ROOT,creationflags=subprocess.CREATE_NO_WINDOW)
base=f'http://127.0.0.1:{port}/'
created=[]
def request(path,cookie=None):
 req=urllib.request.Request(base+path,headers={'Cookie':'PHPSESSID='+cookie} if cookie else {})
 try:
  with opener.open(req,timeout=30) as response: return response.status,response.headers,response.read()
 except urllib.error.HTTPError as error: return error.code,error.headers,error.read()
def compact(text): return re.sub(r'\s+',' ',str(text)).strip()
try:
 for _ in range(50):
  try: request('login.php'); break
  except urllib.error.URLError: time.sleep(.1)
 cookies={}
 for role in ['Manager','Cashier','Inventory Staff']:
  cookies[role]=cli('session',{},role).decode(); created.append(cookies[role])
 for cookie in [None,cookies['Cashier'],cookies['Inventory Staff']]:
  status,headers,body=request('reports_export.php?report=inventory',cookie)
  assert status==302 and headers.get('Location')=='login.php' and not body.startswith(b'%PDF'),(status,body[:100])
 print('PASS: anonymous, Cashier and Inventory Staff direct export access rejected')
 for query in ['report=invalid','report[]=inventory','start_date=2026-02-30','start_date=2026-10-08&end_date=2026-10-07','report=inventory&stock_status=bad','report=inventory&category=Unknown','report=inventory&search[]=milk']:
  status,_,body=request('reports_export.php?'+query,cookies['Manager']); assert status==400,(query,status,body[:100])
 print('PASS: invalid/array/date/range/category/status parameters rejected')
 cases=[('sales',{'report':'sales'}),('sales-cash',{'report':'sales','start_date':'2026-09-06','end_date':'2026-09-12','payment':'cash'}),('sales-qr',{'report':'sales','start_date':'2026-09-06','end_date':'2026-09-12','payment':'qr'}),('inventory',{'report':'inventory'}),('inventory-filtered',{'report':'inventory','search':'Tofu','category':'Proteins','stock_status':'in_stock'}),('inventory-category-spaces',{'report':'inventory','category':'Kitchen Staples'}),('inventory-empty',{'report':'inventory','search':'NoSuchProduct-Export-Test'}),('expiry',{'report':'expiry'}),('expiry-filtered',{'report':'expiry','category':'Proteins','expiry_status':'expired'}),('attendance',{'report':'attendance'}),('attendance-filtered',{'report':'attendance','role':'cashier','attendance_status':'present'}),('attendance-single-day',{'report':'attendance','start_date':'2026-10-01','end_date':'2026-10-01'})]
 for label,query in cases:
  data=json.loads(cli('data',query))
  query=data['filters']; qs=urllib.parse.urlencode(query,quote_via=urllib.parse.quote)
  status,_,html=request('reports.php?'+qs,cookies['Manager']); assert status==200 and b'Export PDF' in html
  assert ('reports_export.php?'+qs.replace('&','&amp;')).encode() in html
  status,headers,pdf=request('reports_export.php?'+qs,cookies['Manager'])
  assert status==200 and headers.get_content_type()=='application/pdf' and pdf.startswith(b'%PDF-'),(label,status,pdf[:200])
  path=ROOT/'tmp/pdfs'/f'{label}.pdf'; path.write_bytes(pdf)
  document=fitz.open(stream=pdf,filetype='pdf'); text=compact(' '.join(p.get_text() for p in document))
  assert 'Generated by:' in text and 'Restoran Kencana Sari' in text
  summaries={'sales':'summary','inventory':'inventorySummary','expiry':'expirySummary','attendance':'attendanceSummary'}
  for key,value in data[summaries[data['activeReport']]].items():
   expected='RM '+f'{float(value):,.2f}' if data['activeReport']=='sales' and key!='total_transactions' else str(value)
   assert expected in text,(label,key,expected)
   assert expected.encode() in html,(label,key,'page mismatch')
  records={'sales':'transactions','inventory':'inventoryRows','expiry':'expiryRows','attendance':'attendanceRows'}
  rows=data[records[data['activeReport']]]
  for row in rows:
   identity=row.get('receipt_no',row.get('product_id',row.get('employee_code')))
   assert identity in text and identity.encode() in html,(label,identity)
   for key in ['product_name','batch_no','full_name','category','stock_status']:
    if key in row: assert compact(row[key]) in text,(label,key)
  assert f'({len(rows)} records)' in text
  for page in document:
   assert re.search(r'Page \d+ of \d+',page.get_text())
   for word in page.get_text('words'):
    assert word[0]>=10*72/25.4 and word[2]<=286*72/25.4 and word[1]>=8*72/25.4 and word[3]<=204*72/25.4,(label,'text outside page bounds',word[:4])
  if label in ['inventory','expiry','sales','attendance']:
   document[0].get_pixmap(matrix=fitz.Matrix(1.4,1.4)).save(str(ROOT/'tmp/pdfs'/f'{label}.png'))
  print('PASS:',label,'page/PDF records and summaries match;',len(rows),'records;',len(document),'PDF pages')
 for label in ['inventory','expiry']:
  document=fitz.open(ROOT/'tmp/pdfs'/f'{label}.pdf')
  document[-1].get_pixmap(matrix=fitz.Matrix(1.4,1.4)).save(str(ROOT/'tmp/pdfs'/f'{label}-last.png'))
 print('PASS: read-only export integration checks')
finally:
 server.terminate(); server.wait(timeout=10); log.close()
 for sid in created:
  path=sessions/('sess_'+sid)
  if path.is_file(): path.unlink()
