CREATE TABLE IF NOT EXISTS leave_requests (
    id INT NOT NULL AUTO_INCREMENT,
    employee_id INT NOT NULL,
    leave_type ENUM('Annual Leave', 'Medical Leave', 'Emergency Leave') NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    status ENUM('Pending', 'Approved', 'Rejected') NOT NULL DEFAULT 'Pending',
    attachment_stored_name VARCHAR(80) NULL,
    attachment_original_name VARCHAR(255) NULL,
    attachment_mime_type VARCHAR(50) NULL,
    attachment_size INT UNSIGNED NULL,
    reviewed_by_user_id INT NULL,
    rejection_reason VARCHAR(1000) NULL,
    submitted_at DATETIME NOT NULL,
    reviewed_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_leave_employee_submitted (employee_id, submitted_at),
    KEY idx_leave_status_submitted (status, submitted_at),
    KEY idx_leave_employee_dates (employee_id, start_date, end_date),
    KEY idx_leave_dates_status (start_date, end_date, status),
    CONSTRAINT fk_leave_requests_employee FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT fk_leave_requests_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT chk_leave_date_range CHECK (end_date >= start_date),
    CONSTRAINT chk_leave_attachment_metadata CHECK ((attachment_stored_name IS NULL AND attachment_original_name IS NULL AND attachment_mime_type IS NULL AND attachment_size IS NULL) OR (attachment_stored_name IS NOT NULL AND attachment_original_name IS NOT NULL AND attachment_mime_type IS NOT NULL AND attachment_size IS NOT NULL)),
    CONSTRAINT chk_leave_medical_attachment CHECK (leave_type <> 'Medical Leave' OR attachment_stored_name IS NOT NULL),
    CONSTRAINT chk_leave_decision_metadata CHECK ((status = 'Pending' AND reviewed_by_user_id IS NULL AND reviewed_at IS NULL AND rejection_reason IS NULL) OR (status = 'Approved' AND reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL AND rejection_reason IS NULL) OR (status = 'Rejected' AND reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL AND rejection_reason IS NOT NULL AND CHAR_LENGTH(TRIM(rejection_reason)) > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
