<?php
require_once __DIR__ . '/reports_pdf.php';

class SecureposAuditPdf extends SecureposReportPdf
{
    public function Footer()
    {
        $this->SetY(-12);
        $this->SetDrawColor(215,225,236);
        $this->Line(12,$this->GetY()-2,285,$this->GetY()-2);
        $this->SetFont('DejaVu','',8);
        $this->SetTextColor(82,100,122);
        $this->Cell(180,6,'SecurePOS | Restoran Kencana Sari | Security Audit Report',0,0);
        $this->Cell(93,6,'Page '.$this->PageNo().' of {nb}',0,0,'R');
    }
}

function buildSecureposAuditPdf(array $data, string $name): SecureposAuditPdf
{
    $pdf=new SecureposAuditPdf('L','mm','A4');
    $pdf->SetMargins(12,12,12);
    $pdf->SetAutoPageBreak(true,18);
    $pdf->AddFont('DejaVu','','DejaVuSans.ttf',true);
    $pdf->AddFont('DejaVu','B','DejaVuSans-Bold.ttf',true);
    $pdf->AliasNbPages();
    $pdf->reportTitle='Audit Log Report';
    $pdf->SetTitle('SecurePOS - Audit Log Report',true);
    $pdf->SetAuthor($name,true);
    $pdf->AddPage();
    $pdf->SetFont('DejaVu','',9);
    $generated=new DateTimeImmutable('now',$data['timezone']);
    $pdf->MultiCell(273,5,'Generated: '.$generated->format('d F Y, g:i A')."\n".'Generated by: '.$name);
    $dateRange = 'All Dates';
    if ($data['startDate'] && $data['endDate']) {
        $dateRange = $data['startDate']->format('d F Y').' – '.$data['endDate']->format('d F Y');
    } elseif ($data['startDate']) {
        $dateRange = 'From '.$data['startDate']->format('d F Y');
    } elseif ($data['endDate']) {
        $dateRange = 'Up to '.$data['endDate']->format('d F Y');
    }
    $pdf->MultiCell(273,5,'Date Range: '.$dateRange);
    $pdf->MultiCell(273,5,'Actor: '.($data['actorSearch']!=='' ? $data['actorSearch'] : 'All Users'));
    $pdf->MultiCell(273,5,'Module: '.$data['moduleOptions'][$data['moduleFilter']].' | Result: '.$data['resultOptions'][$data['resultFilter']].' | Risk: '.$data['riskOptions'][$data['riskFilter']]);
    $pdf->MultiCell(273,5,'Matching audit records: '.count($data['auditRows']));
    $pdf->Ln(5);
    $rows=[];
    foreach ($data['auditRows'] as $row) {
        $when=new DateTimeImmutable($row['created_at'],$data['timezone']);
        $rows[]=[$when->format('d M Y, g:i A'),$row['actor_name'] ?: 'System',$row['actor_role'] ?: 'System',$row['module'],$row['action'],$row['result']==='Failure' ? 'Failed' : $row['result'],$row['risk_level'],$row['description'] ?: 'No description provided.'];
    }
    $pdf->reportTable('Recorded Events',['Date & Time','Actor','Role','Module','Action','Result','Risk Level','Description'],[38,34,28,27,34,20,20,72],$rows);
    return $pdf;
}
